name: Example tests

on:
  push:
    branches:
      - main 

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Verify PHP installation
        run: php -v

      - name: Install dependencies
        run: |
          composer install

      - name: Run Mocha tests
        run: |
          QASE_MODE=testops vendor/bin/phpunit
